# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gsNsNHl0yw1QEcnsypGd8WMaTnZIPCNjF+OoWhXeFqdFASdWcea8HrD1Xqa5sRMKxeaujph51Gn307OSSQSVxgY0anzx54QRAMouxv7Dj55pJwCUObSRK53NPWubuhNEjiFN336nn6JxRmAee3yMLKINmgtiBF9QOn3UBo5KVKEGY1xZlrQ91YJ0AtFW6E/uj9DeP4RAHR5/4LnL8F6QNeoSeB6KAr0hRKMk0Kj4Z3H9QsYevGFnFFFd+bk4DE1IdpqMPYzt+vXImXg7k+cpylWUuNl6wwoMNj3dUOjzTqkQV2BR9JlkV7g+I+AnvrIfBwGh8Ifp7RGLd0S/UYac4ItDmB++MdRA0cDdrOJjswv5lxNZJPElAfU88urLUnflGhkHGseyopSVxt67QC+yKhL3VPMIa9qhMuwbyVlyu1Ov65oGYULUz8xcAB6Ac8/uM+wP4pB1+R0s1YNIcderPwspA/PmOPv3hC3EpLXavoK2NsPQ4bJTW1VhQg3rg3iww3MBU/fb9GX+MguZ8LrtZxslwu+3GkdXc7LTBa5viz43sXSbzU3Uw74vI2tQmQ9RDDXTZyEQ2aHs6x79kcrcGeqkEMF9S7uMnGuxzE7fpf47aFNxK/2MbazqdR+jOFyaF5kCKpWIB/On8rvCUZtQX9KZNz6HTfGmD+eD19BBlVQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
