travis:
  secure:
    BINSTAR_TOKEN: gsNsNHl0yw1QEcnsypGd8WMaTnZIPCNjF+OoWhXeFqdFASdWcea8HrD1Xqa5sRMKxeaujph51Gn307OSSQSVxgY0anzx54QRAMouxv7Dj55pJwCUObSRK53NPWubuhNEjiFN336nn6JxRmAee3yMLKINmgtiBF9QOn3UBo5KVKEGY1xZlrQ91YJ0AtFW6E/uj9DeP4RAHR5/4LnL8F6QNeoSeB6KAr0hRKMk0Kj4Z3H9QsYevGFnFFFd+bk4DE1IdpqMPYzt+vXImXg7k+cpylWUuNl6wwoMNj3dUOjzTqkQV2BR9JlkV7g+I+AnvrIfBwGh8Ifp7RGLd0S/UYac4ItDmB++MdRA0cDdrOJjswv5lxNZJPElAfU88urLUnflGhkHGseyopSVxt67QC+yKhL3VPMIa9qhMuwbyVlyu1Ov65oGYULUz8xcAB6Ac8/uM+wP4pB1+R0s1YNIcderPwspA/PmOPv3hC3EpLXavoK2NsPQ4bJTW1VhQg3rg3iww3MBU/fb9GX+MguZ8LrtZxslwu+3GkdXc7LTBa5viz43sXSbzU3Uw74vI2tQmQ9RDDXTZyEQ2aHs6x79kcrcGeqkEMF9S7uMnGuxzE7fpf47aFNxK/2MbazqdR+jOFyaF5kCKpWIB/On8rvCUZtQX9KZNz6HTfGmD+eD19BBlVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
